// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2hQOd8ODWxjEBWKJM_2Yyyxr0vT44vz4',
    appId: '1:770006746345:web:4902346e1f62efe4ff5c78',
    messagingSenderId: '770006746345',
    projectId: 'food-delivery-danu',
    authDomain: 'food-delivery-danu.firebaseapp.com',
    storageBucket: 'food-delivery-danu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkyZgTCs0q5dnPZfXPILd8Ojos234jlLU',
    appId: '1:770006746345:android:831e80fcacf9de15ff5c78',
    messagingSenderId: '770006746345',
    projectId: 'food-delivery-danu',
    storageBucket: 'food-delivery-danu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArWvKKl5TwdUCdntnbApid9mWr0NDC0e0',
    appId: '1:770006746345:ios:dba18afaa24d3fe0ff5c78',
    messagingSenderId: '770006746345',
    projectId: 'food-delivery-danu',
    storageBucket: 'food-delivery-danu.appspot.com',
    iosClientId: '770006746345-fc1e8a84a74sbclmrihgmf7gg0ul5vmg.apps.googleusercontent.com',
    iosBundleId: 'com.codekaze.app',
  );
}
